- model_name: groq-qwen3.6-27b
  litellm_params:
    model: groq/qwen/qwen3.6-27b
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-gpt-oss-20b
  litellm_params:
    model: groq/openai/gpt-oss-20b
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-gpt-oss-120b
  litellm_params:
    model: groq/openai/gpt-oss-120b
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-gpt-oss-safeguard-20b
  litellm_params:
    model: groq/openai/gpt-oss-safeguard-20b
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-compound
  litellm_params:
    model: groq/compound
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-compound-mini
  litellm_params:
    model: groq/compound-mini
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-whisper-large-v3
  litellm_params:
    model: groq/whisper-large-v3
    api_key: os.environ/GROQ_API_KEY

- model_name: groq-whisper-large-v3-turbo
  litellm_params:
    model: groq/whisper-large-v3-turbo
    api_key: os.environ/GROQ_API_KEY
